# Equal-Weight S&P 500 Index Fund

It will create an algorithm which will accept the value of your portfolio and tell you how many shares of each S&P 500 constituent you should purchase to get an equal-weight version of the index fund.

In [1]:
pip install xlsxwriter

Requirement already satisfied: xlsxwriter in /opt/conda/lib/python3.11/site-packages (3.2.0)
Note: you may need to restart the kernel to use updated packages.

In [1]:
# Import 

import numpy as np
import pandas as pd
import requests
import xlsxwriter
import math

In [31]:
# Import the S&P 500 stocks

stocks = pd.read_csv("sp_500_stocks.csv")

In [3]:
# Acquire an API Token
from config import IEX_CLOUD_API_TOKEN

#Call

# symbol = 'AAPL'
# api_url = f'https://api.polygon.io/v2/aggs/ticker/{symbol}/range/1/day/2023-01-09/2023-01-09?apiKey={IEX_CLOUD_API_TOKEN}'
# data = requests.get(api_url).json()

# print(data)

In [5]:
# price = data['results'][0]['c']
# tot_value = data['results'][0]['v'] * price

In [4]:
# Create DataFrame for Stocks

my_columns = ['Ticker', 'Stock Price', 'Total Traded Value', 'Number of Shares to Buy']
final_dataframe = pd.DataFrame(columns = my_columns)

In [7]:
# final_dataframe.loc[len(final_dataframe)] = [symbol, price, tot_value, 'N/A']

In [8]:
final_dataframe

Empty DataFrame
Columns: [Ticker, Stock Price, Total Traded Value, Number of Shares to Buy]
Index: []

In [27]:
# Loop 
#final_dataframe = pd.DataFrame(columns = my_columns)
for stock in stocks['Ticker'][45:50]:
    api_url = f'https://api.polygon.io/v2/aggs/ticker/{stock}/range/1/day/2023-01-09/2023-01-09?apiKey={IEX_CLOUD_API_TOKEN}'
    data = requests.get(api_url).json()
    final_dataframe.loc[len(final_dataframe)] = [stock, data['results'][0]['c'], data['results'][0]['v']*data['results'][0]['c'], 'N/A']

In [28]:
final_dataframe

   Ticker  Stock Price  Total Traded Value Number of Shares to Buy
0    AAPL     130.1500        9.213424e+09                     N/A
1    NVDA      15.6280        7.879334e+09                     N/A
2    MSFT     227.1200        6.216225e+09                     N/A
3    GOOG      88.8000        2.042105e+09                     N/A
4   GOOGL      88.0200        2.552923e+09                     N/A
5    AMZN      87.3600        5.701643e+09                     N/A
6    META     129.4700        3.447546e+09                     N/A
7    TSLA     119.7700        2.279031e+10                     N/A
8    AVGO      57.6890        2.177110e+09                     N/A
9   BRK.B     315.5300        1.388031e+09                     N/A
10    WMT      48.3167        8.579412e+08                     N/A
11    LLY     349.8300        1.042693e+09                     N/A
12    JPM     137.3700        1.165213e+09                     N/A
13      V     218.6000        1.375985e+09                     N/A
14     MA     370.9700        1.451776e+09                     N/A
15    XOM     108.4700        1.948619e+09                     N/A
16   ORCL      86.4200        6.498642e+08                     N/A
17    UNH     490.0600        1.814585e+09                     N/A
18   COST     478.7500        1.141706e+09                     N/A
19     PG     152.0400        8.707568e+08                     N/A
20     HD     317.8100        1.101614e+09                     N/A
21   NFLX     315.1700        2.132638e+09                     N/A
22    JNJ     175.5800        1.391520e+09                     N/A
23    BAC      33.8900        1.485020e+09                     N/A
24    CRM     147.1000        2.012289e+09                     N/A
25   ABBV     161.6600        1.266276e+09                     N/A
26     KO      62.6100        5.912026e+08                     N/A
27    CVX     175.1800        1.468996e+09                     N/A
28   TMUS     148.7700        7.404423e+08                     N/A
29    MRK     110.3800        1.419351e+09                     N/A
30   CSCO      48.5800        6.771056e+08                     N/A
31    WFC      42.3900        8.997524e+08                     N/A
32    ACN     273.7500        5.971960e+08                     N/A
33    NOW     378.5600        7.884190e+08                     N/A
34    PEP     179.3300        5.952406e+08                     N/A
35     BX      80.5800        3.418951e+08                     N/A
36    AXP     150.4000        4.841987e+08                     N/A
37    MCD     267.2500        7.094314e+08                     N/A
38    IBM     143.5500        5.724461e+08                     N/A
39     MS      87.6400        4.416820e+08                     N/A
40    DIS      94.7700        1.106520e+09                     N/A
41    LIN     321.9200        7.955525e+08                     N/A
42    TMO     546.0900        1.021844e+09                     N/A
43    ABT     112.1500        8.161939e+08                     N/A
44    AMD      67.2400        4.689402e+09                     N/A
45   ADBE     341.9800        1.071703e+09                     N/A
46     GS     353.0000        7.021643e+08                     N/A
47     PM     102.3000        4.976095e+08                     N/A
48   ISRG     264.9300        3.998141e+08                     N/A
49     GE      57.9968        5.503213e+08                     N/A

In [37]:
def chunks(lst, n):
    """
    Yield successive n-sized chunks from lst.
    """
    for i in range(0, len(lst), n):
        yield lst[i:i + n]

In [44]:
symbol_groups = list(chunks(stocks['Ticker'], 10))
symbol_strings = []

for i in range(0, len(symbol_groups)):
    symbol_strings.append(','.join(symbol_groups[i]))
    #print(symbol_strings[i])

AAPL,NVDA,MSFT,GOOG,GOOGL,AMZN,META,TSLA,AVGO,BRK.B
WMT,LLY,JPM,V,MA,XOM,ORCL,UNH,COST,PG
HD,NFLX,JNJ,BAC,CRM,ABBV,KO,CVX,TMUS,MRK
CSCO,WFC,ACN,NOW,PEP,BX,AXP,MCD,IBM,MS
DIS,LIN,TMO,ABT,AMD,ADBE,GS,PM,ISRG,GE

### Calculate the Number of Shares to Buy

In [72]:
portfolio_size = input('Enter the value of your portfolio:')

try:
    val = float(portfolio_size)
    print(val)
except ValueError:
    print("That's not a number! \n Please try again.")
    portfolio_size = input('Enter the value of your portfolio:')
    val = float(portfolio_size)

Enter the value of your portfolio:10000000
10000000.0

In [73]:
position_size = val / len(final_dataframe.index)
print(position_size)

200000.0

In [84]:
for i in range(0, len(final_dataframe.index)):
    final_dataframe.loc[i, 'Number of Shares to Buy'] = math.floor(position_size/final_dataframe.loc[i, 'Stock Price'])

final_dataframe

   Ticker  Stock Price  Total Traded Value Number of Shares to Buy
0    AAPL     130.1500        9.213424e+09                    1536
1    NVDA      15.6280        7.879334e+09                   12797
2    MSFT     227.1200        6.216225e+09                     880
3    GOOG      88.8000        2.042105e+09                    2252
4   GOOGL      88.0200        2.552923e+09                    2272
5    AMZN      87.3600        5.701643e+09                    2289
6    META     129.4700        3.447546e+09                    1544
7    TSLA     119.7700        2.279031e+10                    1669
8    AVGO      57.6890        2.177110e+09                    3466
9   BRK.B     315.5300        1.388031e+09                     633
10    WMT      48.3167        8.579412e+08                    4139
11    LLY     349.8300        1.042693e+09                     571
12    JPM     137.3700        1.165213e+09                    1455
13      V     218.6000        1.375985e+09                     914
14     MA     370.9700        1.451776e+09                     539
15    XOM     108.4700        1.948619e+09                    1843
16   ORCL      86.4200        6.498642e+08                    2314
17    UNH     490.0600        1.814585e+09                     408
18   COST     478.7500        1.141706e+09                     417
19     PG     152.0400        8.707568e+08                    1315
20     HD     317.8100        1.101614e+09                     629
21   NFLX     315.1700        2.132638e+09                     634
22    JNJ     175.5800        1.391520e+09                    1139
23    BAC      33.8900        1.485020e+09                    5901
24    CRM     147.1000        2.012289e+09                    1359
25   ABBV     161.6600        1.266276e+09                    1237
26     KO      62.6100        5.912026e+08                    3194
27    CVX     175.1800        1.468996e+09                    1141
28   TMUS     148.7700        7.404423e+08                    1344
29    MRK     110.3800        1.419351e+09                    1811
30   CSCO      48.5800        6.771056e+08                    4116
31    WFC      42.3900        8.997524e+08                    4718
32    ACN     273.7500        5.971960e+08                     730
33    NOW     378.5600        7.884190e+08                     528
34    PEP     179.3300        5.952406e+08                    1115
35     BX      80.5800        3.418951e+08                    2482
36    AXP     150.4000        4.841987e+08                    1329
37    MCD     267.2500        7.094314e+08                     748
38    IBM     143.5500        5.724461e+08                    1393
39     MS      87.6400        4.416820e+08                    2282
40    DIS      94.7700        1.106520e+09                    2110
41    LIN     321.9200        7.955525e+08                     621
42    TMO     546.0900        1.021844e+09                     366
43    ABT     112.1500        8.161939e+08                    1783
44    AMD      67.2400        4.689402e+09                    2974
45   ADBE     341.9800        1.071703e+09                     584
46     GS     353.0000        7.021643e+08                     566
47     PM     102.3000        4.976095e+08                    1955
48   ISRG     264.9300        3.998141e+08                     754
49     GE      57.9968        5.503213e+08                    3448

### Export into Excel Output

In [85]:
writer = pd.ExcelWriter('recommended_trades.xlsx', engine = 'xlsxwriter')
final_dataframe.to_excel(writer, 'Recommended Trades', index = False)

In [86]:
background_color = '#0a0a23'
font_color = '#ffffff'

string_format = writer.book.add_format(
        {
            'font_color': font_color,
            'bg_color': background_color,
            'border': 1
        }
    )

dollar_format = writer.book.add_format(
        {
            'num_format':'$0.00',
            'font_color': font_color,
            'bg_color': background_color,
            'border': 1
        }
    )

integer_format = writer.book.add_format(
        {
            'num_format':'0',
            'font_color': font_color,
            'bg_color': background_color,
            'border': 1
        }
    )

In [87]:
column_formats = { 
                    'A': ['Ticker', string_format],
                    'B': ['Price', dollar_format],
                    'C': ['Market Capitalization', dollar_format],
                    'D': ['Number of Shares to Buy', integer_format]
                    }

for column in column_formats.keys():
    writer.sheets['Recommended Trades'].set_column(f'{column}:{column}', 20, column_formats[column][1])
    writer.sheets['Recommended Trades'].write(f'{column}1', column_formats[column][0], string_format)

In [88]:
writer.close()